# Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

# Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  );
  
# Q3. Which are the top 5 products with the highest average review rating?
  SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

# Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END) AS discounted_purchases,
    ROUND(
        (SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
             END) * 100.0) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

# Q7. Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segments
GROUP BY customer_segment
ORDER BY
    FIELD(customer_segment, 'New', 'Returning', 'Loyal');
    
# Q8. What are the top 3 most purchased products within each category?
SELECT
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE product_rank <= 3
ORDER BY category, total_purchases DESC;

# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_type, subscription_status
ORDER BY customer_type, subscription_status;

# Q10. What is the revenue contribution of each are group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
Group BY age_group
ORDER BY total_revenue DESC;
